output:
  print-issued-lines: false

linters:
  enable-all: true
  disable:
    - dupword
    - exhaustruct
    - exhaustivestruct
    - funlen
    - gci
    - gochecknoglobals
    - gocognit
    - goimports
    - gofmt
    - gofumpt
    - gomnd
    - maligned
    - nlreturn
    - nolintlint
    - nosnakecase
    - paralleltest
    - revive
    - testpackage
    - varnamelen
    - wsl

linters-settings:
  lll:
    max-length: 100
    tab-width: 2

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-use-default: false
  exclude:
    - "Line contains TODO/BUG/FIXME"
